version: '3'
services:
  vep_rest:
  #  image: dameyerdave/vep-offline-rest
    build: .
    image: dameyerdave/vep-offline-rest
    volumes:
      - '${HOME}/vep_data:/opt/vep/.vep'
      - ./data/images:/opt/vep/src/ensembl-vep/images
      - ./app:/app
    ports:
      - '5005:5005'
