version: '3'
services:
  vep_offline:
    build: 
      context: .
      args: 
        VEP_VERSION: ${VEP_VERSION}
    image: ${DOCKER_IMAGE}:${VEP_VERSION}
    tty: true
    hostname: vep_offline
    volumes:
      - '${HOME}/vep_data:/opt/vep/.vep'
      - ./data/images:/opt/vep/src/ensembl-vep/images
      - ./.installed:/.installed
      - ./app:/app
    ports:
      - '5005:5005'
    env_file:
      - .env
    command:
      - rest
